# how to preview
   # In terminal: hugo server --bind "0.0.0.0" 
   # Visit site: http://127.0.0.1:1313

# new post generation in command line: 
    # hugo new content/posts/your-post-title.md

baseURL = 'https://silvier.org'
languageCode = 'en-us'
title = 'Silvier Linings'
theme = "anubis2"

[pagination]
  pagerSize = 5

[params.author]
  name = "Silvie Senauke"

[[menu.main]]
  name = "Craft Museum"
  url = "/craft-museum/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3


[markup.goldmark.renderer]
  unsafe = true

[params.anubis2]
  customcss = ["css/custom.css"]
  enablecolorthemeswitcher = false
  enablerssicon = false
  enablesummary = true

[params]
  mainSections = ["posts"]
